### ISSUE TITLE
NullRef Exception .Attack_Postfix

### ISSUE THREAD

**Issue by ZenDragonX** [Happydragun4now/DragoonCapes#11]
I am not using any of the capes.  I just have the mod installed.  This happened on login.  Perhaps a monster threw something at me when I logged in?  I'm not sure.  I don't use ranged weapons.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DragoonCapes.einherjarCape.Attack_Postfix (Attack __instance) (at <a118b6598411425cbd0f3d8aee1cc8a1>:0)
(wrapper dynamic-method) Attack.DMD<Attack::OnAttackTrigger>(Attack)
Humanoid.OnAttackTrigger () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
CharacterAnimEvent.Hit () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

**Comment by Happydragun4now** [comment]
Zen was this on a multiplayer server or single player? I've added a fix for this but it's hard to say if its the same issue, please check when I release the next patch if this comes back up.

**Comment by Happydragun4now** [comment]
Added even more safeguards to hopefully prevent this error, closing for now
