### ISSUE TITLE
Deer Cape: Adding +9 bow/crossbow skill instead of 10

### ISSUE THREAD

**Issue by Jester2020** [Happydragun4now/DragoonCapes#12]
Under skills when you equip the Deer cape it shows +9. Tried adjusting the skill in the config but it doesn't change in game.

**Comment by Happydragun4now** [comment]
Please make sure the server side configs aren't overwriting your configs and that you are saving the file and relaunching the game to see the changes.

If neither of those are the issue, please delete the config file and see if it gets remade back to 10% when you next launch the game

**Comment by Jester2020** [comment]
Will test again and get back to you.

**Comment by Jester2020** [comment]
Can't repro this issue. possibly it took time to propagate for some reason. please close the issue

**Comment by Jester2020** [comment]
closing. cannot repro
