### ISSUE TITLE
DragoonCapes.BushCape.Attack_FireProjectileBurst_Prefix 

### ISSUE THREAD

**Issue by Jester2020** [Happydragun4now/DragoonCapes#13]
Here is my Log, includes the list of mods i'm using.  I have a bush cape it was sitting in a box. Not sure what triggered the error unfortunately. When i noticed it i had just left combat and portaled to my base.

Possibly a conflict with CombatOverhaulREwrite.Patches.ProjectilePatch.OnHit_Prefix 

[Message:   BepInEx] BepInEx 5.4.22.0 - valheim (12/24/2023 10:42:41 AM)
[Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2202 from Thunderstore
[Info   :   BepInEx] Running under Unity v2022.3.12.5236448
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] Loaded 1 patcher method from [ConfigWatcher 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [ShutUp 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [StartupAccelerator 1.0.0.0]
[Info   :   BepInEx] 4 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 90 plugins to load
[Info   :   BepInEx] Loading [PlantEverything 1.16.2]
[Info   :   BepInEx] Loading [Craft From Containers 3.5.0]
[Info   :   BepInEx] Loading [Show Container Contents 0.4.0]
[Info   :   BepInEx] Loading [AzuDevMod 1.0.6]
[Info   :   BepInEx] Loading [AzuExtendedPlayerInventory 1.3.12]
[Info   :   BepInEx] Loading [AzuMiscPatches 1.2.2]
[Info   :   BepInEx] Loading [AzuSigns 1.0.5]
[Info   :   BepInEx] Loading [AzuSkillTweaks 1.0.3]
[Info   :   BepInEx] Loading [AzuWorkbenchTweaks 1.0.2]
[Info   :   BepInEx] Loading [DeathPinRemoval 1.0.4]
[Info   :   BepInEx] Loading [ImFRIENDLYDAMMIT 1.1.2]
[Info   :   BepInEx] Loading [LogKeeper 1.0.0]
[Info   :   BepInEx] Loading [PerformanceTracker 1.0.3]
[Info   :   BepInEx] Loading [Recycle_N_Reclaim 1.3.1]
[Info   :   BepInEx] Loading [ResourceUnloadOptimizer 1.0.3]
[Info   :   BepInEx] Loading [BalrondHumanoidRandomizer 1.2.2]
[Info   :   BepInEx] Loading [BowPlugin 1.7.3]
[Info   :   BepInEx] Loading [Dual Wield 1.0.9]
[Info   :   BepInEx] Loading [CombatOverhaulREwrite 1.1.8]
[Info   :   BepInEx] Loading [Herbalist 1.3.2]
[Info   :   BepInEx] Loading [LazyVikings 1.0.8]
[Info   :   BepInEx] Loading [LootParticlePlus 1.1.0]
[Info   :   BepInEx] Loading [MagicPlugin 1.8.5]
[Info   :   BepInEx] Loading [ComfyGizmo 1.9.0]
[Info   :   BepInEx] Loading [GimmeFuelGimmeFire 0.0.5]
[Info   :   BepInEx] Loading [Configuration Manager 18.2]
[Info   :   BepInEx] Loading [Jotunn 2.16.2]
[Info   :   BepInEx] Loading [MissingPieces 2.0.7]
[Info   :   BepInEx] Loading [InfiniteTorches 0.0.1]
[Info   :   BepInEx] Loading [DragoonCapes 1.2.8]
[Info   :   BepInEx] Loading [FenceSnap 0.3.0]
[Info   :   BepInEx] Loading [MultiUserChest 0.5.7]
[Info   :   BepInEx] Loading [Pressure-Plate 0.9.2]
[Info   :   BepInEx] Loading [VNEI 0.14.1]
[Info   :   BepInEx] Loading [LocationReset 0.8.0]
[Info   :   BepInEx] Loading [Better Wisps 1.0.26]
[Info   :   BepInEx] Loading [Epic Loot 0.9.37]
[Info   :   BepInEx] Loading [Digitalroot's Bounties 3.0.9]
[Info   :   BepInEx] Loading [Digitalroot's Slope Combat Assistance 2.0.22]
[Info   :   BepInEx] Loading [NoAFKEvents 1.0.2]
[Info   :   BepInEx] Loading [Loyal Spears - Auto Pickup And Return To Owner 1.0.1]
[Info   :   BepInEx] Loading [Quick Stack - Store - Sort - Trash - Restock 1.4.5]
[Info   :   BepInEx] Loading [Sorted Cooking, Crafting and Skills Menu 1.3.3]
[Info   :   BepInEx] Loading [More Gates 1.0.10]
[Info   :   BepInEx] Loading [OdinShipPlus 0.4.7]
[Info   :   BepInEx] Loading [BetterUI 2.5.4]
[Info   :   BepInEx] Loading [Simple Sailing 1.1.0]
[Info   :   BepInEx] Loading [Speedy Paths Mod 1.0.8]
[Info   :   BepInEx] Loading [Blacksmithing 1.2.5]
[Info   :   BepInEx] Loading [Building 1.2.5]
[Info   :   BepInEx] Loading [Cooking 1.1.15]
[Info   :   BepInEx] Loading [Creature Level & Loot Control 4.5.19]
[Info   :   BepInEx] Loading [Darwin Awards 1.0.6]
[Info   :   BepInEx] Loading [Evasion 1.0.3]
[Info   :   BepInEx] Loading [Exploration 1.0.2]
[Info   :   BepInEx] Loading [Farming 2.1.12]
[Info   :   BepInEx] Loading [FoodCustomizer 1.0.4]
[Info   :   BepInEx] Loading [Foraging 1.0.8]
[Info   :   BepInEx] Loading [GapFiller 1.0.4]
[Info   :   BepInEx] Loading [Groups 1.2.6]
[Info   :   BepInEx] Loading [Lumberjacking 1.0.5]
[Info   :   BepInEx] Loading [Mining 1.1.5]
[Info   :   BepInEx] Loading [PackHorse 1.0.3]
[Info   :   BepInEx] Loading [Passive Powers 1.0.12]
[Info   :   BepInEx] Loading [Ranching 1.1.3]
[Info   :   BepInEx] Loading [Sailing 1.1.7]
[Info   :   BepInEx] Loading [Smooth Save 1.0.5]
[Info   :   BepInEx] Loading [Spearfishing 1.0.2]
[Info   :   BepInEx] Loading [Tenacity 1.0.3]
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[Info   :   BepInEx] Loading [Projectile Collision 1.6]
[Info   :   BepInEx] Loading [Almanac 3.1.5]
[Info   :   BepInEx] Loading [Server Devcommands 1.74]
[Info   :   BepInEx] Loading [Server Sync Fix 1.3]
[Info   :   BepInEx] Loading [JustSleep 1.0.2]
[Info   :   BepInEx] Loading [Protective Wards 1.1.10]
[Info   :   BepInEx] Loading [Seasons 1.1.0]
[Info   :   BepInEx] Loading [Traders Extended 1.0.20]
[Info   :   BepInEx] Loading [Smoke Collision 1.8]
[Info   :   BepInEx] Loading [DvergrPieces 2.6.1]
[Info   :   BepInEx] Loading [Warfare 1.6.6]
[Info   :   BepInEx] Loading [Armory 1.1.7]
[Info   :   BepInEx] Loading [Monstrum 1.3.4]
[Info   :   BepInEx] Loading [WarfareFireAndIce 1.1.4]
[Info   :   BepInEx] Loading [MonstrumAshlands 1.1.5]
[Info   :   BepInEx] Loading [MonstrumDeepNorth 1.1.6]
[Info   :   BepInEx] Loading [Upgrade World 1.47]
[Info   :   BepInEx] Loading [Shield Me Bruh! 1.0.8]
[Info   :   BepInEx] Loading [Comfort Tweaks 3.2.10]
[Info   :   BepInEx] Loading [XPortal 1.2.20]
[Message:   BepInEx] Chainloader startup complete
[Info   :StartupAccelerator] Batch-patched 690 methods after Chainloader end in 4320 ms
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Warning:Server Sync Fix] Mod Tequila.DvergrPieces has outdated server sync.
[Warning:Server Sync Fix] Updated server sync for Tequila.DvergrPieces.
[Warning:Server Sync Fix] Updated server sync for Tequila.DvergrPieces PieceManager.
[Warning:Server Sync Fix] Mod vapok.mods.shieldmebruh has outdated server sync.
[Warning:Server Sync Fix] Updated server sync for vapok.mods.shieldmebruh.
[Info   :StartupAccelerator] Batch-patched 252 methods after FejdStartup.Awake in 810 ms
[Warning:DragoonCapes] Mod Statuses Enabled: True
[Warning: Unity Log] Unable to load font face for [Norse SDF]. Make sure "Include Font Data" is enabled in the Font Import Settings.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DragoonCapes.BushCape.Attack_FireProjectileBurst_Prefix (Attack __instance) (at <0677be0b2c3c4aeca444ceb584a8929c>:0)
(wrapper dynamic-method) Attack.DMD<Attack::FireProjectileBurst>(Attack)
(wrapper dynamic-method) Attack.DMD<Attack::ProjectileAttackTriggered>(Attack)
(wrapper dynamic-method) Attack.DMD<Attack::OnAttackTrigger>(Attack)
Humanoid.OnAttackTrigger () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
CharacterAnimEvent.OnAttackTrigger () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
CombatOverhaulREwrite.Patches.ProjectilePatch.OnHit_Prefix (Projectile __instance, UnityEngine.Collider collider, UnityEngine.Vector3 hitPoint, System.Boolean water) (at <06ae174f1a7e4b50af2ead5a7d440660>:0)
(wrapper dynamic-method) Projectile.DMD<Projectile::OnHit>(Projectile,UnityEngine.Collider,UnityEngine.Vector3,bool)
Projectile.FixedUpdate () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

[Info   : Unity Log] 02/17/2024 17:18:01: Cloud Save: 87923 bytes. /characters/jester test two.fch.new

[Info   : Unity Log] 02/17/2024 17:18:01: Steam writing file chunks 1 / 1, (87923 bytes)

[Info   : Unity Log] 02/17/2024 17:18:01: Steam Cloud Move: 76996 bytes. /characters/jester test two.fch -> /characters/jester test two.fch.old

[Info   : Unity Log] 02/17/2024 17:18:01: Steam writing file chunks 1 / 1, (76996 bytes)

[Info   : Unity Log] 02/17/2024 17:18:01: Steam Cloud Move: 87923 bytes. /characters/jester test two.fch.new -> /characters/jester test two.fch

[Info   : Unity Log] 02/17/2024 17:18:01: Steam writing file chunks 1 / 1, (87923 bytes)

[Info   : Unity Log] 02/17/2024 17:18:01: Cloud Copy: 87923 bytes. characters/jester test two.fch -> characters/jester test two_backup_auto-20240217171801.fch

[Info   : Unity Log] 02/17/2024 17:18:01: Steam writing file chunks 1 / 1, (87923 bytes)

**Comment by Jester2020** [comment]
I"m trying to get you some repro steps but here is the error again. I do have a Bush Cape, i am not wearing it when this happened.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DragoonCapes.BushCape.Attack_FireProjectileBurst_Prefix (Attack __instance) (at <0677be0b2c3c4aeca444ceb584a8929c>:0)
(wrapper dynamic-method) Attack.DMD<Attack::FireProjectileBurst>(Attack)
(wrapper dynamic-method) Attack.DMD<Attack::ProjectileAttackTriggered>(Attack)
(wrapper dynamic-method) Attack.DMD<Attack::OnAttackTrigger>(Attack)
Humanoid.OnAttackTrigger () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
CharacterAnimEvent.OnAttackTrigger () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DragoonCapes.BrawlerCape.JotunnPunch_Prefix (HitData hit) (at <0677be0b2c3c4aeca444ceb584a8929c>:0)
(wrapper dynamic-method) Character.DMD<Character::Damage>(Character,HitData)
Aoe.OnHit (UnityEngine.Collider collider, UnityEngine.Vector3 hitPoint) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Aoe.CheckHits () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Aoe.Start () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DragoonCapes.BushCape.Attack_FireProjectileBurst_Prefix (Attack __instance) (at <0677be0b2c3c4aeca444ceb584a8929c>:0)
(wrapper dynamic-method) Attack.DMD<Attack::FireProjectileBurst>(Attack)
(wrapper dynamic-method) Attack.DMD<Attack::ProjectileAttackTriggered>(Attack)
(wrapper dynamic-method) Attack.DMD<Attack::OnAttackTrigger>(Attack)
Humanoid.OnAttackTrigger () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
CharacterAnimEvent.OnAttackTrigger () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

**Comment by Happydragun4now** [comment]
Okay I added safeguards that should make these errors impossible to happen, closing issue for now
