### ISSUE TITLE
Null Ref Error

### ISSUE THREAD

**Issue by ZenDragonX** [Happydragun4now/DragoonCapes#15]
This happened when just loading the game.  I do not actually have that cape instanced anywhere in the world.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DragoonCapes.BrawlerCape.JotunnPunch_Prefix (HitData hit) (at <fc13e5fd66db4751bc87a521717888d5>:0)
(wrapper dynamic-method) Character.DMD<Character::Damage>(Character,HitData)
Aoe.OnHit (UnityEngine.Collider collider, UnityEngine.Vector3 hitPoint) (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Aoe.CheckHits () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Aoe.FixedUpdate () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

**Comment by Happydragun4now** [comment]
Should be fixed with 1.3.1, please re-open if it continues
