### ISSUE TITLE
Thank you for updating so quickly!

### ISSUE THREAD

**Issue by So1207** [Happydragun4now/DragoonCapes#17]
As soon as I found out that an update was available, I downloaded it and applied it right away. I'm glad it seems to be going well.
I responded with an improved translation right after I received the reply, but I think it was too late. There is version 3 that I reported in an already closed issue. I couldn't understand the strangely translated content and words, so I translated the missing parts. I guess I was a little too hasty as this was my first attempt... I'm gradually increasing the number of your versions...😱
I don't know how to end this. thank you!

**Comment by Happydragun4now** [comment]
No problem, thanks again for the translation!
I'll put the new file in the next update
