### ISSUE TITLE
Neck Skin Cape's immunity to wet doesn't work

### ISSUE THREAD

**Issue by goktug-ocalan** [Happydragun4now/DragoonCapes#19]
I just made the Neck Skin Cape, which says that it will give `Immune vs Wet`, `Swim +30` and `Resistant VS Poison`

The other two effects seems to be working but I'm still getting the wet status effect. `NeckWaterproof` is set to `true` in the config. Am I missing something?

![Screenshot 2024-04-17 123516](https://github.com/Happydragun4now/DragoonCapes/assets/76447165/6f1f9cdf-f058-4488-918c-d189fb97c4da)

![Screenshot 2024-04-17 123557](https://github.com/Happydragun4now/DragoonCapes/assets/76447165/d66c615d-b49a-4de3-b162-a1b56bb2127a)

**Comment by Happydragun4now** [comment]
Thanks for this, I found the issue, It will be fixed with the next update
