### ISSUE TITLE
Stalker Cape | Possible translations

### ISSUE THREAD

**Issue by Pjoter1991** [Happydragun4now/DragoonCapes#2]
1. Hi, Stalker Cape keeps spamming console during night and I'm not sure it works (I don't think it actually raises bow skill). Screenshot attached.

2. Is it possible to make translation for your mod, and if yes, would you be willing to share english file so I can make one?
![StalkerCapeErrors](https://github.com/Happydragun4now/DragoonCapes/assets/139540247/e13d8221-fba4-4490-a3fe-ab68c7387638)

**Comment by Happydragun4now** [comment]
Sorry those were my testing messages, I'll remove them for the next update

**Comment by Happydragun4now** [comment]
I decided to do localization, I will release the english file with the next update, please let me know if you make a localization so I can upload it, would be much appreciated

**Comment by Pjoter1991** [comment]
[Polish.json](https://github.com/Happydragun4now/DragoonCapes/files/14068806/Polish.json)
There you go.
