### ISSUE TITLE
Issue with EpicLoot, while wearing the Einheriar cloak and using axe with throwing enchantment. - Axe vanishes completely on impact.

### ISSUE THREAD

**Issue by AoD-Karl** [Happydragun4now/DragoonCapes#20]
Hey, first I want to appreciate the amazing mod that you made for us!

I found a issue, I think conflicting with EpicLoot, while wearing the Einheriar cloak and using throwing enchantment.

I use an axe with throwing and recallling enchantment, the throwing appears to use the same mechanics as spears do and it gets the buffed projectile speed as well. 
But instead of returning as it always did, the axe instead vanishes completely, even when thrown just at the floor at my feet. 
If infinite throwing is disabled all is back to normal. Looks like infinite throwing makes the projectile disappear, but since its an axe and not a spear I do not get a new one... Same for all weapons I tested.  (Spears of course work just fine^^)

Not a big problem so far, I tried to understand what mechanics were used but Logs showed nothing different with the effect enabled / disabled. Looks to me like everything is running as intended so far. 

Best Regards,
Karl

**Comment by Happydragun4now** [comment]
Fixed for the next update!

I made all thrown weapons act as the spears do
