### ISSUE TITLE
List of Cape Names

### ISSUE THREAD

**Issue by KyleMHB** [Happydragun4now/DragoonCapes#21]
Hi could you add a list of cape names into your readme? Actual item names so that I can reference them - I see you have a table on ThunderStore, it would be amazing if you could just add them in there.
I need to add them all to a enchantment config (valheim enchantment system)

https://thunderstore.io/c/valheim/p/KGvalheim/Valheim_Enchantment_System/

**Comment by Happydragun4now** [comment]
Done for the next update!
