### ISSUE TITLE
Mod incompatible with Ashlands update

### ISSUE THREAD

**Issue by id11100** [Happydragun4now/DragoonCapes#23]
Loading with the mod leads to strange camera behaviour.

**Conditions**
Enable only these mods:
- BepInEx
- Jotunn
- DragoonCapes

**Steps to reproduce**
Create new character
Launch new world

**Result**
Camera is shaking insanely
Character is sitting, not responding to controls
Character HP is 100

**Alternative scenario**
If launched with existing character, these problems occur in addition to previously mentioned:
- all inventory items are gone
- character resets to default one (naked, white skin, bald and no facial hair)

_Thank you in advance!_

**Comment by PaloAlo** [comment]
same results as above on v1.3.1 and game version 218.15

**Comment by Happydragun4now** [comment]
Should be fixed with 1.3.2
Thanks for reporting!
