### ISSUE TITLE
Icons and items show incorrectly

### ISSUE THREAD

**Issue by Percel32** [Happydragun4now/DragoonCapes#24]
![obraz_2024-05-16_125900818](https://github.com/Happydragun4now/DragoonCapes/assets/121593561/5b76e554-0ceb-4d98-b5a9-de2e280dc446)
Objects are displayed incorrectly on the screen.

**Comment by Percel32** [comment]
Overall, the capes have a vanilla look, they do not look like the ones in the picture.

**Comment by JocelynBrunel** [comment]
The tooltips also appear incorrectly.

**Comment by DravenFrostfall** [comment]
Same issues for me

**Comment by Aspendosia** [comment]
Same for me too.

**Comment by KidSith** [comment]
Hope this gets fixed soon

**Comment by OgKowboy** [comment]
Yep same issue, tooltips missing, missing textures and icons. I see in the mod itself on Thunderstore has an empty assets file, only thing in it is the .dll looking forward to a complete re upload :)

**Comment by ZenDragonX** [comment]
same issue

**Comment by Happydragun4now** [comment]
I reuploaded 1.3.3 with the textures.

Sorry everyone this was a really dumb mistake on my side, but fixed now :)
