### ISSUE TITLE
Only New cape showing is Neck Cape

### ISSUE THREAD

**Issue by Xanomenon** [Happydragun4now/DragoonCapes#25]
Installed the mod today. Learned Neck Cape when I logged in. Vanilla capes updated, but couldn't find any of the other new capes. I have EasySpawner installed and tried to look up to see if I could find the other capes and figure out if I needed to touch something to learn how to make a newer one, but none of the others showed up as existing in the game at all.

**Comment by Happydragun4now** [comment]
Please try VNEI and make sure jotunn is updated as well, the 1.3.3 is working with all the capes, please let me know if you see any difference using VNEI

**Comment by Xanomenon** [comment]
![image](https://github.com/Happydragun4now/DragoonCapes/assets/138287633/fcc77584-eb15-4d17-92a0-bcd9ec8cdb00)
Still only the Neck.

**Comment by Xanomenon** [comment]
Searched "Cape"

**Comment by Xanomenon** [comment]
We also tried to go back to an earlier version and still no go

**Comment by Xanomenon** [comment]
Found out.. it was Balrond's Cultist Armor.
