### ISSUE TITLE
Enabled // Disabled Capes

### ISSUE THREAD

**Issue by heberholanda** [Happydragun4now/DragoonCapes#3]
It would be interesting to be able to enable and disable the covers. 

You can also change the Adventurer Cape benefits to benefits like the others.

**Comment by Happydragun4now** [comment]
by covers do you mean the new textures/icons, that could be a cool config if people are interested.

ATM I don't have plans to change the adventurer cape, I think it has a good place but im worried ppl will just take it as a bedroll inventory slot.

**Comment by Bumbletr0n** [comment]
Hello, Happydragun, love your work. 
How can I remove the 'infinite throw' perk on the Einherjar cape?
IMO, I consider it to be quite overpowered as it removes all incentive to use a bow.

Thanks!

**Comment by Happydragun4now** [comment]
> Hello, Happydragun, love your work. How can I remove the 'infinite throw' perk on the Einherjar cape? IMO, I consider it to be quite overpowered as it removes all incentive to use a bow.
> 
> Thanks!

Sure I'll make a config value for it next update
