### ISSUE TITLE
How should I translate it into Chinese?

### ISSUE THREAD

**Issue by zzh377442** [Happydragun4now/DragoonCapes#4]
I'm a Chinese player, I hope there will be a Chinese translation version, I can help with the translation, can you tell me the translation method?

**Comment by Happydragun4now** [comment]
I decided to do localization, I will release the english file with the next update, please let me know if you make a localization so I can upload it, would be much appreciated

**Comment by jneb802** [comment]
Hey @Happydragun4now, I'm a big fan of your mod and would love to help do your translations. I made a [script](https://github.com/jneb802/valheim_GPT_Localization) that uses GPT to translate a mod into many Valheim languages. I just translated Almanac using this method. If you using JSONs then I'd be happy to translate for you as well.
