### ISSUE TITLE
Adventure Cape On/Off

### ISSUE THREAD

**Issue by Jester2020** [Happydragun4now/DragoonCapes#5]
Apologies as I didn't know where to add a feature request. The Adventure Cape only has a toggle for rested On/Off. This is a very powerful buff. Would it be possible when turned on to also have a multiplier option so there would be an option that's it's not a permanent buff but based on your base rested and the multiplier.

Sorry again if this is the wrong place for this. Fantastic mod by the way, really adds flavor to capes.

**Comment by Jester2020** [comment]
Any thoughts on the complexity of adding this change? I like the idea of an extended rested bonus but 100% on is a bit powerful. Thanks!

**Comment by Happydragun4now** [comment]
Recent update I reworked adventurer cape to have a comfort bonus instead of perm-rested, for those who want to keep perma rested they can set the comfort bonus to 1000 in the configs.

More balanced this way I think lol

**Comment by Jester2020** [comment]
Perfect! Thank you. Thanks for being easy to work with on these things.

**Comment by ZenDragonX** [comment]
The comfort bonus is a nice fix.  One problem:  I noticed you can just sit down and apply the bonus and then take the cape off while still seated and it keeps the long bonus.  This doesn't happen if you take the cape off while not seated.  So it may need some additional work to make it so players can't just put the cape on for 2 seconds to get max comfort timer and then take it off and wear a different cape instead.

**Comment by Happydragun4now** [comment]
Fixed both issues as of 1.3.0 as per my own testing, please re-open if issue comes back
