### ISSUE TITLE
install on server causes all creatures to deal no damage

### ISSUE THREAD

**Issue by Naduk72** [Happydragun4now/DragoonCapes#7]
when run on clients and server, all mobs fail to deal damage and errors are thrown 
work around is to run only configs on server and mod+config on clients, however this is insecure and should be addressed

**Comment by Happydragun4now** [comment]
Hi what other mods do you have installed, I have tested this on my own server with friends and haven't run into this

**Comment by Happydragun4now** [comment]
Hi I added more safeguards to the mod but can't be sure if it will fix this issue as I wasn't able to reproduce it. Closing for now
